name: Deploy website

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-website.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: deploy-frontend-session
          aws-region: ${{secrets.AWS_REGION}}

      - name: Build App
        run: |
          npm install
          npm run build
        working-directory: Frontend

      - name: Deploy to AWS S3
        run: aws s3 sync . s3://${{ secrets.WEBSITE_BUCKET_NAME }} --delete
        working-directory: Frontend/dist
        