name: Deploy website

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-website.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: deploy-frontend-session
          aws-region: ${{secrets.AWS_REGION}}

      - name: Package artifact
        run: zip -r ./website.zip *
        working-directory: Frontend

      - name: list files
        run: |
            cd Frontend
            ls -la
            
      - name: Upload artifact to S3
        run: |
          cd Frontend
          aws s3 cp website.zip s3://${{ secrets.WEBSITE_BUCKET_NAME }}/application-${{ github.run_id }}.zip